### ISSUE TITLE
评论显示两次ip

### ISSUE THREAD

**Issue by cc123687** [Hill-98/userscripts#1]
[https://img1.imgtp.com/2023/06/17/bG4hThPQ.png](url)

**Comment by Hill-98** [comment]
麻烦提供下发生问题的网址

**Comment by cc123687** [comment]
> 麻烦提供下发生问题的网址

[https://www.bilibili.com/video/BV1XN41167Bv/](url)
随便一个视频都这样

**Comment by Hill-98** [comment]
我这里并没有复现这个问题，能提供下你所使用的浏览器吗？

**Comment by cc123687** [comment]
> 我这里并没有复现这个问题，能提供下你所使用的浏览器吗？

Google Chrome
版本 78.0.3904.97（正式版本） （64 位）

**Comment by Hill-98** [comment]
@cc123687 嗯。。。如果方便的话，建议你使用最新的 Chrome/Edge/FireFox 浏览器，这个版本太老了，即使我的脚本不兼容此浏览器版本，我也不会去修复。

**Comment by cc123687** [comment]
> @cc123687 嗯。。。如果方便的话，建议你使用最新的 Chrome/Edge/FireFox 浏览器，这个版本太老了，即使我的脚本不兼容此浏览器版本，我也不会去修复。

好吧
