### ISSUE TITLE
视频页不显示IP了

### ISSUE THREAD

**Issue by KuiPer-LTW** [Hill-98/userscripts#3]
很奇怪，前段时间动态页出过问题，现在又轮到视频页了，是我的问题吗

**Comment by Hill-98** [comment]
我提交了个新版本，你可以试试，不过我这里新旧版本都没问题。

**Comment by KuiPer-LTW** [comment]
> 我提交了个新版本，你可以试试，不过我这里新旧版本都没问题。

也许是我的问题，因为今天又好了

**Comment by Hill-98** [comment]
那就好
